services:
  nexa:
    image: ghcr.io/nexirift/nexa:develop
    build: .
    container_name: nexa
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./data/clamav:/var/lib/clamav
